[package]
name = "nativehelper"
version = "0.3.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
clap = {version = "4.4.11", features = ["derive"]}
steamworks = "0.10.0"
websocket = "0.27.0"
